// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: subgenre.proto
// Protobuf Java Version: 4.27.1

package com.example.library_spring.proto;

public final class SubGenreProto {
  private SubGenreProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      SubGenreProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubGenreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SubGenre)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .Genre genre = 3;</code>
     * @return Whether the genre field is set.
     */
    boolean hasGenre();
    /**
     * <code>optional .Genre genre = 3;</code>
     * @return The genre.
     */
    com.example.library_spring.proto.GenreProto.Genre getGenre();
    /**
     * <code>optional .Genre genre = 3;</code>
     */
    com.example.library_spring.proto.GenreProto.GenreOrBuilder getGenreOrBuilder();
  }
  /**
   * Protobuf type {@code SubGenre}
   */
  public static final class SubGenre extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SubGenre)
      SubGenreOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        SubGenre.class.getName());
    }
    // Use SubGenre.newBuilder() to construct.
    private SubGenre(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SubGenre() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.library_spring.proto.SubGenreProto.internal_static_SubGenre_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.library_spring.proto.SubGenreProto.internal_static_SubGenre_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.library_spring.proto.SubGenreProto.SubGenre.class, com.example.library_spring.proto.SubGenreProto.SubGenre.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENRE_FIELD_NUMBER = 3;
    private com.example.library_spring.proto.GenreProto.Genre genre_;
    /**
     * <code>optional .Genre genre = 3;</code>
     * @return Whether the genre field is set.
     */
    @java.lang.Override
    public boolean hasGenre() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .Genre genre = 3;</code>
     * @return The genre.
     */
    @java.lang.Override
    public com.example.library_spring.proto.GenreProto.Genre getGenre() {
      return genre_ == null ? com.example.library_spring.proto.GenreProto.Genre.getDefaultInstance() : genre_;
    }
    /**
     * <code>optional .Genre genre = 3;</code>
     */
    @java.lang.Override
    public com.example.library_spring.proto.GenreProto.GenreOrBuilder getGenreOrBuilder() {
      return genre_ == null ? com.example.library_spring.proto.GenreProto.Genre.getDefaultInstance() : genre_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getGenre());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGenre());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.library_spring.proto.SubGenreProto.SubGenre)) {
        return super.equals(obj);
      }
      com.example.library_spring.proto.SubGenreProto.SubGenre other = (com.example.library_spring.proto.SubGenreProto.SubGenre) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasGenre() != other.hasGenre()) return false;
      if (hasGenre()) {
        if (!getGenre()
            .equals(other.getGenre())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGenre()) {
        hash = (37 * hash) + GENRE_FIELD_NUMBER;
        hash = (53 * hash) + getGenre().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.library_spring.proto.SubGenreProto.SubGenre parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.library_spring.proto.SubGenreProto.SubGenre prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SubGenre}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SubGenre)
        com.example.library_spring.proto.SubGenreProto.SubGenreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.library_spring.proto.SubGenreProto.internal_static_SubGenre_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.library_spring.proto.SubGenreProto.internal_static_SubGenre_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.library_spring.proto.SubGenreProto.SubGenre.class, com.example.library_spring.proto.SubGenreProto.SubGenre.Builder.class);
      }

      // Construct using com.example.library_spring.proto.SubGenreProto.SubGenre.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getGenreFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        name_ = "";
        genre_ = null;
        if (genreBuilder_ != null) {
          genreBuilder_.dispose();
          genreBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.library_spring.proto.SubGenreProto.internal_static_SubGenre_descriptor;
      }

      @java.lang.Override
      public com.example.library_spring.proto.SubGenreProto.SubGenre getDefaultInstanceForType() {
        return com.example.library_spring.proto.SubGenreProto.SubGenre.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.library_spring.proto.SubGenreProto.SubGenre build() {
        com.example.library_spring.proto.SubGenreProto.SubGenre result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.library_spring.proto.SubGenreProto.SubGenre buildPartial() {
        com.example.library_spring.proto.SubGenreProto.SubGenre result = new com.example.library_spring.proto.SubGenreProto.SubGenre(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.library_spring.proto.SubGenreProto.SubGenre result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.genre_ = genreBuilder_ == null
              ? genre_
              : genreBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.library_spring.proto.SubGenreProto.SubGenre) {
          return mergeFrom((com.example.library_spring.proto.SubGenreProto.SubGenre)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.library_spring.proto.SubGenreProto.SubGenre other) {
        if (other == com.example.library_spring.proto.SubGenreProto.SubGenre.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasGenre()) {
          mergeGenre(other.getGenre());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getGenreFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.example.library_spring.proto.GenreProto.Genre genre_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.library_spring.proto.GenreProto.Genre, com.example.library_spring.proto.GenreProto.Genre.Builder, com.example.library_spring.proto.GenreProto.GenreOrBuilder> genreBuilder_;
      /**
       * <code>optional .Genre genre = 3;</code>
       * @return Whether the genre field is set.
       */
      public boolean hasGenre() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       * @return The genre.
       */
      public com.example.library_spring.proto.GenreProto.Genre getGenre() {
        if (genreBuilder_ == null) {
          return genre_ == null ? com.example.library_spring.proto.GenreProto.Genre.getDefaultInstance() : genre_;
        } else {
          return genreBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public Builder setGenre(com.example.library_spring.proto.GenreProto.Genre value) {
        if (genreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          genre_ = value;
        } else {
          genreBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public Builder setGenre(
          com.example.library_spring.proto.GenreProto.Genre.Builder builderForValue) {
        if (genreBuilder_ == null) {
          genre_ = builderForValue.build();
        } else {
          genreBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public Builder mergeGenre(com.example.library_spring.proto.GenreProto.Genre value) {
        if (genreBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            genre_ != null &&
            genre_ != com.example.library_spring.proto.GenreProto.Genre.getDefaultInstance()) {
            getGenreBuilder().mergeFrom(value);
          } else {
            genre_ = value;
          }
        } else {
          genreBuilder_.mergeFrom(value);
        }
        if (genre_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public Builder clearGenre() {
        bitField0_ = (bitField0_ & ~0x00000004);
        genre_ = null;
        if (genreBuilder_ != null) {
          genreBuilder_.dispose();
          genreBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public com.example.library_spring.proto.GenreProto.Genre.Builder getGenreBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getGenreFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      public com.example.library_spring.proto.GenreProto.GenreOrBuilder getGenreOrBuilder() {
        if (genreBuilder_ != null) {
          return genreBuilder_.getMessageOrBuilder();
        } else {
          return genre_ == null ?
              com.example.library_spring.proto.GenreProto.Genre.getDefaultInstance() : genre_;
        }
      }
      /**
       * <code>optional .Genre genre = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.library_spring.proto.GenreProto.Genre, com.example.library_spring.proto.GenreProto.Genre.Builder, com.example.library_spring.proto.GenreProto.GenreOrBuilder> 
          getGenreFieldBuilder() {
        if (genreBuilder_ == null) {
          genreBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.library_spring.proto.GenreProto.Genre, com.example.library_spring.proto.GenreProto.Genre.Builder, com.example.library_spring.proto.GenreProto.GenreOrBuilder>(
                  getGenre(),
                  getParentForChildren(),
                  isClean());
          genre_ = null;
        }
        return genreBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SubGenre)
    }

    // @@protoc_insertion_point(class_scope:SubGenre)
    private static final com.example.library_spring.proto.SubGenreProto.SubGenre DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.library_spring.proto.SubGenreProto.SubGenre();
    }

    public static com.example.library_spring.proto.SubGenreProto.SubGenre getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubGenre>
        PARSER = new com.google.protobuf.AbstractParser<SubGenre>() {
      @java.lang.Override
      public SubGenre parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubGenre> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubGenre> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.library_spring.proto.SubGenreProto.SubGenre getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubGenre_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SubGenre_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016subgenre.proto\032\013genre.proto\"d\n\010SubGenr" +
      "e\022\017\n\002id\030\001 \001(\003H\000\210\001\001\022\021\n\004name\030\002 \001(\tH\001\210\001\001\022\032\n" +
      "\005genre\030\003 \001(\0132\006.GenreH\002\210\001\001B\005\n\003_idB\007\n\005_nam" +
      "eB\010\n\006_genreB1\n com.example.library_sprin" +
      "g.protoB\rSubGenreProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.library_spring.proto.GenreProto.getDescriptor(),
        });
    internal_static_SubGenre_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubGenre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SubGenre_descriptor,
        new java.lang.String[] { "Id", "Name", "Genre", });
    descriptor.resolveAllFeaturesImmutable();
    com.example.library_spring.proto.GenreProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
